eval_prompt = """
Please act as an impartial judge and evaluate the quality of the response provided with respect
to the details provided. You will rate the quality of the response on multiple aspects, such as
Helpfulness, Clarity, Factuality, Depth and Engagement. The response has been provided by an AI
agent for a query related to an input audio, which the agent can perceive. You will be provided
with 4 kinds of information for evaluating the response:
1. A list where each comma-separated element indicates the individual events occurring in the
audio at various time segments. For example, '(Speech-0.0-0.64)' would mean human speech
between 0.0 second to 0.64 second.
2. A caption of the audio describing in a brief and abstract manner the scene in which the
audio takes place.
3. The question asked to the AI agent related to the audio.
4.An answer provided by an expert judge which you can consider as a reference.
5. An answer by the AI agent.
##Query: [query]
## Evaluate
### Aspects
- Clarity: Rate the response based on how well-structured it is, with ideas presented in a
clear and coherent manner. A high score of 5 means the answer is clear and logically
structured, while a 1 suggests a disjointed or confusing reply.
- Correctness: Evaluate the correctness or accuracy of the response provided with respect to
the information provided to you. A perfect 5 indicates the response is entirely correct and
accurate, while a 1 suggests it has significant errors or has not provided an answer to the
question asked at all.
- Depth: Determine the level of detail and thoroughness in the response. A score of 5 means
the answer delves deeply into the aspects of the input image for answering the question, while
a 1 indicates it barely scratches the surface.
### Format
### Given the query and the extra information about the audio provided (the caption and commaseparated list of individual individual events), please rate the quality of the output by
scoring it from 1 to 5, individually on **each aspect**. You are allowed to use all 3
information provided to you about the audio, in any way you want, to judge the response.
Now, please output your scores in the following json format by filling in the placeholders in
[].
{ 'clarity':{ 'reason': '[your rationale]', 'score': '[score from 1 to 5]' }, 'correctness': { 'reason':'[your rationale]', 'score': '[score from 1 to 5]' }, 'engagement': { 'reason': '[your rationale]', 'score': '[score from 1 to 5]' } }
Only return the json and nothing else."
"""

temp_prompt = """
I want you to act as a Caption Evaluator. I will provide you with an audio caption generated by an AI agent.
The agent was asked to generate a dense and detailed caption of the audio. To evaluate the caption, I will provide you five scene captions of the audio describing in a brief and abstract manner the scene in which the audio takes place.
You should first extract semantic templates for five scene captions, and then extract semantic templates for generated captions. The semantic template extraction procedure is describe below:
### Semantic template extraction procedure
Given a caption and sound events within the caption, extract relationships among sound events by using the following template: [sound event| temporal relationship| sound event].\n\nThere are two possible temporal relationships: concurrent with and following by.\n\nConcurrent with defines the temporal relationship that two audio events occur simultaneously.\n\nFollowing by defines the temporal relationship that one event occurs after the other event.\n\nIf there is an event occurring repeatedly, the output should be: [event| following by| same event]

Some examples:
    caption: Constant rattling noise and sharp vibrations -> semantic template: [Rattle| concurrent with| vibration]
    caption: An infant crying followed by a man laughing -> semantic template: [Infant cry| following by| laughter]
### End procedure
Finally, you should count how many [sound event| temporal relationship| sound event] match between generated caption template and each scene caption templates.
Given answer in JSON format: {scene_caption i: #number_match/#event_relation}
[query]
"""
